import { useState } from 'react';
import { colleges, states, dataNote } from '../data/admissions';
import { track } from '../data/config';
export default function CollegeExplorer() {
  const [state, setState] = useState(''), [query, setQuery] = useState(''), [management, setManagement] = useState('');
  const visible = colleges.filter(c => c.published && c.source_urls?.length && c.last_updated && (!state || c.state === state) && (!management || c.management_type === management) && `${c.college_name} ${c.city} ${c.state}`.toLowerCase().includes(query.toLowerCase()));
  const datum = (c, field, year) => c[field] != null && c[year] && c.source_urls?.length ? `${c[field]} (${c[year]})` : 'Check current details';
  return <section id="colleges" className="bg-slate-50"><div className="content-wrap"><p className="eyebrow">MEDICAL COLLEGE EXPLORER</p><h2>Compare medical colleges with the details that actually matter.</h2>
    <div className="college-filters"><label>State<select value={state} onChange={e => setState(e.target.value)}><option value="">All states</option>{states.map(s => <option key={s.slug}>{s.name}</option>)}</select></label><label>Search colleges<input type="search" placeholder="Search medical college, city or state" value={query} onChange={e => setQuery(e.target.value)} /></label><label>Management<select value={management} onChange={e => setManagement(e.target.value)}><option value="">All types</option>{['Government', 'Private', 'Deemed'].map(x => <option key={x}>{x}</option>)}</select></label></div>
    {visible.length ? <div className="discovery-grid">{visible.map(c => <article className="discovery-card" key={c.slug}><h3>{c.college_name}</h3><p>{c.city}, {c.state} · {c.management_type}</p><dl>{[['Annual Tuition', 'annual_tuition', 'fee_year'], ['MBBS Seats', 'mbbs_seats', 'seat_year'], ['Previous Closing Rank', 'closing_rank_or_range', 'cutoff_year']].map(([label, field, year]) => <div key={field}><dt>{label}</dt><dd>{datum(c, field, year)}</dd></div>)}</dl><p>{c.counselling_authority}</p><p>Last updated: {c.last_updated}</p><a href={c.source_urls[0]}>Official source →</a><a className="primary-button" href="/#counselling" onClick={() => track('check_chances_click')}>Check My Chances →</a></article>)}</div> : <div className="empty-data"><h3>{state ? `Explore your options in ${state}` : 'Start with your state and counselling route.'}</h3><p>No verified college records are published for this selection yet. Build your profile to discuss a shortlist, or check the official college directory for current institution details.</p><div className="section-actions"><a href="/#counselling" className="primary-button" onClick={() => track('check_chances_click')}>Check My Chances →</a><a href="https://www.nmc.org.in/information-desk/college-and-course-search/" className="text-link">Open NMC College Directory ↗</a></div></div>}
    <p className="data-note">{dataNote}</p></div></section>;
}
