import { ArrowRight } from 'lucide-react';
import { referenceFiles, referenceNote, contentReviewDate } from '../data/addition-content';
import { stateFeeReferences } from '../data/state-fee-references';
import CollegeExplorer from './CollegeExplorer';
import ProfileConversion from './ProfileConversion';
import { TopicIcon, CollegeCrest, StateShape } from './Visuals';
import { BadgeCheck, Wallet, FileText } from 'lucide-react';

export default function StateAdmissionContent({ state }) {
  const fees = stateFeeReferences[state.name];
  const maharashtra = state.name === 'Maharashtra';
  const sections = [
    ['counselling-routes', 'COUNSELLING ROUTES', 'Know which application you need.', state.routeCopy, state.authorityUrl, `${state.authority} ↗`],
    ['state-eligibility', 'ELIGIBILITY', 'Check your exact seat category.', 'Review NEET eligibility and AIR, domicile or schooling requirements, category documents and the rules for the seat you are considering. Compare state, management, minority and NRI routes where offered; the college list alone does not determine which route you qualify for.', state.authorityUrl, 'Read the current state bulletin ↗'],
    ['state-fees', 'FEES & COMPLETE COST', 'Keep fee periods and quotas separate.', `${state.feeCopy} Confirm tuition, hostel, mess, deposits, other charges, escalation and the number of chargeable years before estimating a complete budget.`, '/tools/mbbs-cost-calculator/', 'Build your own cost estimate →'],
    ['state-cutoffs', 'CUTOFF REFERENCES', 'Use AIR and the right result edition.', `${maharashtra ? 'The Maharashtra PDF explicitly uses 2025 trends and projected 2026 score bands. It is not a final 2026 cutoff list.' : 'Poster scores do not establish a complete result year, category and quota. They are not presented as official 2026 closing scores.'} Compare published closing AIR for your category, seat quota and round through official result lists. A fixed marks-to-rank conversion or guaranteed chance is not inferred.`, state.authorityUrl, 'Check official allotment results ↗'],
    ['state-documents', 'DOCUMENTS & REPORTING', 'Prepare before choice filling.', 'Organise your NEET admit card/scorecard, identity documents, Class 10/12 records and relevant domicile, category or quota documents. Check certificate formats, registration payment, choice locking, reporting instructions and refund conditions in the current bulletin.', '/tools/counselling-checklist/', 'Use the counselling checklist →'],
    ['state-locations', 'LOCATION & TRAINING', 'Compare daily life and clinical exposure.', `Explore locations including ${state.cities.join(', ')}. Ask about the teaching hospital, clinical rotations, internship structure, accommodation and travel. Compare evidence from each institution rather than relying on promotional stars or broad rankings.`, '#colleges', `Explore ${state.name} college references →`],
  ];
  return <><section className="bg-white section-decor state-plan-section"><StateShape name={state.name} className="section-state-watermark" /><div className="content-wrap">
    <p className="eyebrow">YOUR STATE ADMISSION PLAN</p><h2>Start with the route, then compare colleges.</h2><p className="section-copy">{state.intro}</p>
    <div className="reference-tabs"><a href="#counselling-routes">Routes & eligibility</a><a href="#state-fees">Fees & budget</a><a href="#colleges">College references</a><a href="#state-documents">Documents</a><a href="#state-faqs">FAQs</a></div>
    <div className="state-guide-grid">{sections.map(([id, label, title, copy, href, link], index) => <article id={id} className="state-guide-block" key={id}><div className="state-guide-head"><TopicIcon title={label} /><span className="reference-badge">{String(index + 1).padStart(2, '0')} · {label}</span></div><h3>{title}</h3><p>{copy}</p><a className="text-link" href={href}>{link}</a>{index === 0 && <a className="text-link" href="https://mcc.nic.in/ug-medical-counselling/">MCC counselling notices ↗</a>}</article>)}</div>
    <p className="data-note">Overview reviewed {contentReviewDate}. Official links are provided for confirmation. Supplied college fees, seats and poster scores remain separately labelled planning references.</p>
  </div></section>
  {fees && <section className="bg-slate-50"><div className="content-wrap"><p className="eyebrow">SUPPLIED STATE FEE REFERENCES</p><h2>{state.name} poster fee table.</h2><p className="section-copy">{fees.period}. These transcribed values are separate from the workbook entries below.</p><p className="reference-note">{referenceNote} {fees.note}</p>
    <div className="reference-table-scroll" role="region" aria-label={`${state.name} poster fee table`} tabIndex={0}><table className="reference-table"><caption>{state.name} · JNEX supplied poster · {fees.period}</caption><thead><tr>{fees.columns.map(column => <th scope="col" key={column}>{column}</th>)}</tr></thead><tbody>{fees.rows.map((row, index) => <tr key={index}>{row.map((value, col) => col === 0 ? <th scope="row" key={col}><span className="table-college"><CollegeCrest name={value} className="crest-sm" />{value}</span></th> : <td key={col}>{value}</td>)}</tr>)}</tbody></table></div>
    <details className="poster-reference"><summary>View the original poster and source notes</summary><p className="reference-note">{state.feeCopy}{state.name === 'Karnataka' ? ' The original contains an incorrect Andhra Pradesh footer.' : ''} {fees.note}</p><a className="text-link" href={referenceFiles[state.poster]} download>Download original image</a><img src={referenceFiles[state.poster]} alt={`Original supplied ${state.name} medical college reference poster; readable fee transcription appears above`} loading="lazy" /></details>
  </div></section>}
  {state.name === 'Karnataka' && <section id="bengaluru" className="bg-white"><div className="content-wrap"><p className="eyebrow">BENGALURU & NEARBY OPTIONS</p><h2>A location-based shortlist to discuss.</h2><p className="section-copy">The supplied Bengaluru poster names Akash, Oxford, East Point, BGS, Vydehi, MVJ, Sri Chamundeshwari and Dr. B. R. Ambedkar medical colleges. Confirm each campus location and current seat route; the list includes a nearby Karnataka option beyond Bengaluru.</p><ul className="crest-chips">{['Akash', 'Oxford', 'East Point', 'BGS', 'Vydehi', 'MVJ', 'Sri Chamundeshwari', 'Dr. B. R. Ambedkar'].map(name => <li key={name}><CollegeCrest name={name} className="crest-sm" />{name}</li>)}</ul><p className="reference-note">The poster’s “total fees under ₹60 lakh” and “NEET 350+” statements are not confirmed complete-cost quotes or admission predictions. Compare the applicable quota and additional costs for each institution.</p><a className="text-link" href="#colleges">Search the Karnataka college references below <ArrowRight size={15} aria-hidden="true" /></a></div></section>}
  {maharashtra && <section id="state-funding" className="bg-slate-50"><div className="content-wrap"><p className="eyebrow">MAHARASHTRA FUNDING & ROUTES</p><h2>Plan fees, applications and funding separately.</h2><div className="discovery-grid">
    <article className="discovery-card"><h3>State CAP and MCC</h3><p>The supplied guide compares Maharashtra private/state options with participating deemed options through MCC. Use current authority bulletins to confirm your registration route and eligibility.</p><a className="text-link" href="/mbbs-admission/#admission-routes">Compare admission routes</a></article>
    <article className="discovery-card"><h3>Registration and security deposits</h3><p>Keep application charges and refundable security deposits separate from tuition. The guide’s quoted charges are estimates; check current payment and forfeiture rules before registration.</p><a className="text-link" href="https://mcc.nic.in/ug-medical-counselling/">Open current MCC notices ↗</a></article>
    <article className="discovery-card"><h3>Scholarships and reimbursements</h3><p>Explore MahaDBT schemes by category, income, institution and admission route. A fee waiver is not a relaxation in admission merit or an automatic award.</p><a className="text-link" href="/scholarships/#maharashtra-funding">Review Maharashtra funding questions</a></article>
    </div><div className="section-actions"><a className="primary-button" href="/resources/#maharashtra-mbbs">Open the Maharashtra planning guide <ArrowRight size={16} aria-hidden="true" /></a><a className="text-link" href="/deemed-university-mbbs/">Explore deemed college references</a></div></div></section>}
  <CollegeExplorer full initialState={state.name} />
  <section id="state-faqs" className="bg-white"><div className="content-wrap"><h2>{state.name} admission questions.</h2><div className="state-guide-faqs">{state.faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></div></section>
  <ProfileConversion initialProfile={{ domicile: state.name }} /></>;
}

export function MaharashtraFunding() {
  return <section id="maharashtra-funding" className="bg-slate-50"><div className="content-wrap"><p className="eyebrow">MAHARASHTRA MEDICAL EDUCATION</p><h2>Check the scheme before counting on a waiver.</h2><p className="section-copy">The supplied Maharashtra guide discusses category-based tuition support and girls’ fee reimbursement. MahaDBT lists medical education and category-specific schemes; eligibility must be checked against the exact scheme.</p>
    <div className="discovery-grid">{[['Check eligibility', 'Confirm domicile, category, income, institution type, admission route and the scheme’s current conditions.'], ['Understand coverage', 'Distinguish tuition and examination support from hostel, mess, deposits and other charges. Ask whether you must pay upfront and claim reimbursement.'], ['Prepare an application', 'Check income/category/domicile documents, allotment proof, bank details, college verification and renewal conditions. Track your application through the provider.']].map(([title, copy], index) => <article className="discovery-card icon-card" key={title}><span className="icon-badge" aria-hidden="true">{[<BadgeCheck key="e" strokeWidth={1.7} />, <Wallet key="c" strokeWidth={1.7} />, <FileText key="a" strokeWidth={1.7} />][index]}</span><h3>{title}</h3><p>{copy}</p></article>)}</div>
    <div className="section-actions"><a className="primary-button" href="https://mahadbt.maharashtra.gov.in/">Explore official MahaDBT schemes ↗</a><a className="text-link" href="/mbbs-admission/maharashtra/">Back to Maharashtra MBBS planning</a></div><p className="data-note">No blanket “free MBBS” eligibility or guaranteed reimbursement is claimed. Verify current scheme details and college implementation before making a payment decision.</p>
  </div></section>;
}
